# Generated by Django 4.1.6 on 2023-03-15 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=500)),
                ('addressline1', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=500)),
                ('country_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=500, null=True)),
                ('lastname', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('is_admin', models.BooleanField(default=True)),
                ('ifLogged', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.    Unselect this instead of deleting accounts.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Establishment_type', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('operater_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('promocode', models.CharField(blank=True, max_length=500, null=True)),
                ('discount_rate', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_agreement_form', models.FileField(blank=True, null=True, upload_to='agreement_form/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='signature/')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to='products_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('role', models.CharField(choices=[('DISPATCHER', 'dispatcher'), ('USER', 'customer')], default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('attribute_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('password', models.CharField(max_length=250)),
                ('position', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('ifLogged', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(choices=[('ONETIME', 'OneTime'), ('MEMBERSHIP', 'Membership')], default='ONETIME', max_length=500)),
                ('service_type_description', models.TextField(max_length=1000, null=True)),
                ('price', models.FloatField(null=True)),
                ('service_agreement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.serviceagreement')),
            ],
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=250)),
                ('service_datetime', models.DateTimeField()),
                ('service_fee', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('requested_service_datetime', models.DateTimeField()),
                ('Establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.operater')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.servicetype'),
        ),
        migrations.CreateModel(
            name='Promotion_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.promotion')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=500)),
                ('unit_number', models.CharField(max_length=500)),
                ('addressline1', models.CharField(max_length=500)),
                ('addressline2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=500)),
                ('country_name', models.CharField(max_length=500)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=250, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=250, null=True, region=None)),
                ('establishment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishment',
            name='establishment_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment_type'),
        ),
        migrations.CreateModel(
            name='Customer_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
