# Generated by Django 3.2.12 on 2022-12-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attribute_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
