# Generated by Django 3.2.12 on 2023-01-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Establishment_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='squarefeet',
            new_name='square_feet',
        ),
        migrations.AddField(
            model_name='establishment',
            name='establishment_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment_type'),
            preserve_default=False,
        ),
    ]
