# Generated by Django 4.1.6 on 2023-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispatcher',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dispatcher', 'dispatcher'), ('customer', 'customer')], default='', max_length=50),
        ),
    ]
