# Generated by Django 3.2.12 on 2022-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_decision', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='add_unit',
        ),
    ]
