# Generated by Django 3.2.12 on 2023-01-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0002_auto_20230109_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='service_type_description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicelist', to='Mobile_Inspectionapp.serviceagreement'),
        ),
    ]
