# Generated by Django 3.2.12 on 2023-01-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0002_auto_20230111_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addressline2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
    ]
