# Generated by Django 4.1.5 on 2023-01-21 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0002_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.address'),
        ),
        migrations.CreateModel(
            name='Establishment_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=250, null=True)),
                ('Establishment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment')),
            ],
        ),
    ]
