# Generated by Django 4.1.6 on 2023-03-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadaddress',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='promotion_category',
            name='promotion_id',
        ),
        migrations.RemoveField(
            model_name='promotion_category',
            name='service_type_id',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='Establishment_id',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='operater_id',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadAddress',
        ),
        migrations.DeleteModel(
            name='Operater',
        ),
        migrations.DeleteModel(
            name='Promotion_Category',
        ),
        migrations.DeleteModel(
            name='Service_Order',
        ),
    ]
