# Generated by Django 3.2.12 on 2022-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_auto_20221213_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricalInspectableItem',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
