# Generated by Django 3.2.12 on 2022-11-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_auto_20221114_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
