# Generated by Django 4.1.5 on 2023-01-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_alter_establishment_address_id_establishment_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment_contact',
            old_name='Establishment_id',
            new_name='establishment_id',
        ),
    ]
