# Generated by Django 3.2.12 on 2023-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_auto_20230109_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='service_type_description',
        ),
    ]
