# Generated by Django 3.2.12 on 2023-01-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0003_auto_20230111_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer_id',
        ),
    ]
