# Generated by Django 3.2.12 on 2023-01-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0004_remove_servicetype_service_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='service_type_description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.serviceagreement'),
        ),
    ]
