# Generated by Django 3.2.12 on 2023-01-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0005_auto_20230111_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='square_feet',
        ),
    ]
