# Generated by Django 4.1.6 on 2023-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('dispatcher', 'dispatcher'), ('customer', 'customer')], default='', max_length=50, null=True),
        ),
    ]
