# Generated by Django 4.1.5 on 2023-01-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0006_alter_establishment_establishment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment_contact',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.user'),
        ),
    ]
