# Generated by Django 3.2.12 on 2022-11-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0006_auto_20221115_0453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decision',
            new_name='Services',
        ),
    ]
