# Generated by Django 3.2.12 on 2023-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0006_remove_establishment_square_feet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='service_type_name',
            field=models.CharField(choices=[('ONETIME', 'OneTime'), ('MEMBERSHIP', 'Membership')], default='ONETIME', max_length=500),
        ),
    ]
