# Generated by Django 4.1.6 on 2023-03-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('dispatcher', 'dispatcher'), ('customer', 'customer')], default='customer', max_length=50, null=True),
        ),
    ]
