# Generated by Django 3.2.12 on 2023-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0007_alter_servicetype_service_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(blank=True, upload_to='products_images/'),
        ),
    ]
