# Generated by Django 4.1.6 on 2023-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.BooleanField(default=False),
        ),
    ]
