# Generated by Django 3.2.12 on 2023-01-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0007_rename_item_cart_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='service_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.service'),
            preserve_default=False,
        ),
    ]
