# Generated by Django 3.2.12 on 2022-11-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0007_rename_decision_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='add_decision',
            new_name='services',
        ),
    ]
