# Generated by Django 3.2.12 on 2022-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0008_rename_add_decision_services_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalInspectableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
            ],
        ),
    ]
