# Generated by Django 4.1.5 on 2023-01-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0008_alter_establishment_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.address'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.user'),
        ),
    ]
