# Generated by Django 3.2.12 on 2023-01-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0008_alter_service_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.CreateModel(
            name='Service_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(blank=True, upload_to='products_images/')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.service')),
            ],
        ),
    ]
