# Generated by Django 4.1.6 on 2023-03-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0008_user_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_by',
            new_name='user_created_by',
        ),
    ]
