# Generated by Django 3.2.12 on 2023-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0009_auto_20230111_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service_image',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='service_agreement_form',
            field=models.FileField(blank=True, null=True, upload_to='agreement_form/'),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature/'),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
