# Generated by Django 4.1.6 on 2023-03-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0009_rename_created_by_user_user_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_created_by',
            new_name='user_created_by_admin',
        ),
    ]
