# Generated by Django 3.2.12 on 2023-01-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0010_auto_20230111_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.address'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.user'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='establishment_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment_type'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
