# Generated by Django 4.1.6 on 2023-03-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0010_rename_user_created_by_user_user_created_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=500)),
            ],
        ),
    ]
