# Generated by Django 3.2.12 on 2023-01-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0011_alter_contact_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
