# Generated by Django 4.1.6 on 2023-03-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0012_operater_operater_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operater',
            name='operater_type',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date_time', models.DateTimeField()),
                ('service_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('establishment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment')),
                ('operater_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.operater')),
                ('service_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.servicetype')),
            ],
        ),
    ]
