# Generated by Django 4.1.6 on 2023-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0013_alter_operater_operater_type_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatcher_user_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
