# Generated by Django 4.1.6 on 2023-03-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0015_operater_dispatcher_id_serviceitem_dispatcher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='establishment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.establishment'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='operater_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.operater'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mobile_Inspectionapp.servicetype'),
        ),
    ]
