# Generated by Django 4.1.5 on 2023-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0015_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to='products_images/')),
            ],
        ),
    ]
