# Generated by Django 4.1.5 on 2023-01-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0021_alter_establishment_establishment_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment_contact',
            name='customer_id',
        ),
    ]
