# Generated by Django 4.1.5 on 2023-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_Inspectionapp', '0022_remove_establishment_contact_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ifLogged',
            field=models.BooleanField(default=True),
        ),
    ]
